- webAO/master.html
> literally not readable

- webAO/client.css
- webAO/client.html
- webAO/client.js
- webAO/golden/css/goldenlayout.css
this fixed #20  the issue i just opened
> Resizing fix

- webAO/client.html
Users actually get trouble with refreshing stuff on their side, it should be made in here. We could automatize the change of versions, but maybe later.
If you make drastic changes in `client` files, make sure to change version number(s) in `client.html` before deploying for production.
> Urgent cache busting

- webAO/master.js
> Fix onmouseover after moving master.js to Webpack

- webAO/client.js
this is a small one
i removed the `this.resources.map` part as it was throwing exceptions and doesn't look like it was used anywhere.
> move resource loading and spectator code

- webAO/client.css
- webAO/client.js
- webAO/index.html
- webAO/master.js
OK so this fixes the TODOs on
- blips
- shownames
by loading the ini file asynchronously when the client gets to parsing the char name.
It stores the ini file with the character, which will use up a little more RAM but will speed up loading a new character.
In addition the client will flip the name upside down in the charselect, to give the user a hint that this character can't be used.
Characters with missing charicons will show up as a name that can be clicked, instead of the placeholder ? sign like it was before.
> blips, shownames, charicons and async loading

- webAO/client.js
> New stands

- webAO/client.html
- webAO/client.js
Reverts AttorneyOnline/webAO#34
> Revert "fuck"

- webAO/client.css
- webAO/client.js
finally something that works better on webAO than on the client
> animated rainbow text

- webAO/client.css
- webAO/client.js
> area updates

- webAO/client.js
> Tick cleanup

- webAO/client.html
- webAO/client.js
- webAO/styles/client.css
the new charselect
- fits on narrow screens
- is centered
- works on more devices than before
> Charselect

- webAO/client.js
- webAO/styles/client.css
i tested it in nox with android 5 and the try catch around the promise works really well
> Png support

- webAO/styles/client.css
> use vw for icon size

- webAO/client.html
- webAO/client.js
- webAO/encoding.js
- webAO/styles/client.css
> Music search

- webAO/client.html
- webAO/client.js
- webAO/styles/client.css
> Character search

- webAO/client.html
- webAO/client.js
> Testimony volume

- webAO/client.html
- webAO/client.js
adds ambience and the 2 extra channels. server can also control if the music loops or not
> add channels and clientside looping

- webAO/client.js
only works with custom.gif in the characters folder and the duration is hardset to 840
but it's better than not working at all
> Custom shout

- webAO/client.html
- webAO/client.js
- webAO/styles/nameplates.css
- webAO/styles/shownames.css
HAHAHAHA IT DOESN'T LAG THE FUCK OUT OF EVERYTHING, TAKE THIS CLIENT
> Showname switch

- webAO/encoding.js
- webAO/index.html
- webAO/master.js
ok so basically only check the playercount (and reachability) when you hover your mouse over the list
> Less ms spam

- webAO/client.js
Is this even used by any servers at all?
> Remove FC packet

- webAO/client.html
- webAO/client.js
- webAO/styles/client.css
> Fullsize bg

- webAO/client.js
- webAO/encoding.js
- webAO/master.js
- webAO/services/request.js
- webAO/utils/calculateGifLength.js
- webAO/utils/calculateWebpLength.js
- webAO/utils/calculatorHandler.js
- webAO/utils/getCookie.js
- webAO/utils/setCookie.js
This was intended to fix WEBP preanimations. 
WEBP preanimations are supported in this, but they're incredibly shakey.
This PR resolves an issue where if a character has multiple different file extensions, they would all play overlapped on one another making the image look like it was lagging behind. It now tries to load each one from an array and the first one that loads is displayed.
This PR also includes some code rearranging to pull more functions/etc out of `client.js` ⚔️
> WebAO Partial Image Fixes

- webAO/client.js
Blip slider collected the value but never assigned it to the channels
> Fix blip slider to actually work

- package.json
- public/client.html
- tsconfig.json
- webAO/client.js
- webAO/encoding.ts
- webAO/master.ts
- webAO/utils/aoml.ts
> Sypetcript

- webAO/client.js
- webAO/services/__tests__/downloadFile.test.ts
- webAO/services/downloadFile.ts
Added support for `/save_chatlog` command. Also added the ability to expand and add other commands to webAO in the future if wanted.
> Added support for saving chatlog

- webAO/client.js
https://cdn.discordapp.com/attachments/807014767407267892/957061854469967973/2022-03-25_19-37-31.mp4
> WebAO has Non-interrupting Preanimations | I've been to hell and back

- tsconfig.json
- webAO/client.ts
- webAO/dom/changeVolume.js
- webpack.config.js
yeah let me fuck up all other PRs real quick
> Typescript client.js

- webAO/client.ts
There may be a better fix since I really am unfamiliar with this language and codebase, but this fixed it well enough.
Closes #139
> Reveal the textbox after the preanimation

- webAO/client.ts
- webAO/dom/cancelEvidence.ts
- webAO/dom/changeBackgroundOOC.ts
- webAO/dom/changeCallwords.ts
- webAO/dom/editEvidence.ts
- webAO/dom/getIndexFromSelect.ts
- webAO/dom/iniEdit.ts
- webAO/dom/modCallTest.ts
- webAO/dom/pickEmotion.ts
- webAO/dom/pickEvidence.ts
- webAO/dom/switchPanTilt.ts
- webAO/dom/toggleShout.ts
- webAO/dom/updateEvidenceIcon.ts
- webAO/packets/handlers/handleBN.ts
- webAO/packets/handlers/handlePV.ts
1339 lines in one file is better than before!
> Added more functions

- webAO/client.ts
- webAO/dom/addEvidence.ts
- webAO/dom/addHPD.ts
- webAO/dom/addHPP.ts
- webAO/dom/callMod.ts
- webAO/dom/changeCharacter.ts
- webAO/dom/changeRoleOOC.ts
- webAO/dom/charError.ts
- webAO/dom/charTableFilter.ts
- webAO/dom/deleteEvidence.ts
- webAO/dom/guilty.ts
- webAO/dom/imgError.ts
- webAO/dom/initCE.ts
- webAO/dom/initWT.ts
- webAO/dom/notGuilty.ts
- webAO/dom/pickChar.ts
- webAO/dom/randomCharacterOOC.ts
- webAO/dom/reconnectButton.ts
- webAO/dom/redHPD.ts
- webAO/dom/redHPP.ts
- webAO/dom/setChatbox.ts
- webAO/dom/switchAspectRatio.ts
- webAO/dom/switchChatOffset.ts
- webAO/dom/toggleMenu.ts
- webAO/dom/window.ts
- webAO/viewport.ts
I did a lot of files at once because I got tired of small PR's. Client.ts is now officially not the largest file in webAO, clocking in at 986 lines compared to viewport.ts at 1092.
> Removed all window functions from client

- webAO/client.ts
- webAO/client/sender/index.ts
- webAO/client/sender/sendIC.ts
- webAO/client/sender/sendSelf.ts
- webAO/client/sender/sendServer.ts
- webAO/dom/changeBackgroundOOC.ts
- webAO/dom/changeRoleOOC.ts
- webAO/dom/onEnter.ts
- webAO/packets/handlers/handleCC.ts
- webAO/packets/handlers/handleCI.ts
- webAO/packets/handlers/handleEI.ts
- webAO/packets/handlers/handleEM.ts
- webAO/packets/handlers/handleHI.ts
- webAO/packets/handlers/handleID.ts
- webAO/packets/handlers/handlePN.ts
- webAO/packets/handlers/handleRC.ts
- webAO/packets/handlers/handleRD.ts
- webAO/packets/handlers/handleRM.ts
- webAO/packets/handlers/handleSC.ts
- webAO/packets/handlers/handleSI.ts
- webAO/packets/handlers/handleSM.ts
- webAO/packets/handlers/handleaskchaa.ts
Abstracting out the sending functions into their own module to reduce amount of code in client.
> Grouping Sending Functions

- webAO/client.ts
- webAO/client/addTrack.ts
- webAO/client/appendICLog.ts
- webAO/client/checkCallword.ts
- webAO/client/createArea.ts
- webAO/client/fetchLists.ts
- webAO/client/fixLastArea.ts
- webAO/client/handleBans.ts
- webAO/client/handleCharacterInfo.ts
- webAO/client/isAudio.ts
- webAO/client/isLowMemory.ts
- webAO/client/loadResources.ts
- webAO/client/resetICParams.ts
- webAO/client/saveChatLogHandle.ts
- webAO/client/sender/sendOOC.ts
- webAO/dom/iniEdit.ts
- webAO/dom/showNameClick.ts
- webAO/packets/handlers/handleBD.ts
- webAO/packets/handlers/handleCI.ts
- webAO/packets/handlers/handleEM.ts
- webAO/packets/handlers/handleFA.ts
- webAO/packets/handlers/handleFM.ts
- webAO/packets/handlers/handleKB.ts
- webAO/packets/handlers/handleKK.ts
- webAO/packets/handlers/handleMC.ts
- webAO/packets/handlers/handleMS.ts
- webAO/packets/handlers/handleSC.ts
- webAO/packets/handlers/handleSM.ts
- webAO/packets/handlers/handleackMS.ts
- webAO/viewport.ts
Now I think we can group functions into individual files as we see fit and add functions back to client. 
Also, I'm going to start working on viewport
> Client at 297 lines

- .github/workflows/deploy.yml
- webAO/client.ts
- webAO/client/loadResources.ts
- webAO/client/setEmote.ts
- webAO/dom/changeMusicVolume.ts
- webAO/dom/reloadTheme.ts
- webAO/packets/handlers/handleMS.ts
- webAO/packets/handlers/handleRT.ts
- webAO/viewport/interfaces/ChatMsg.ts
- webAO/viewport/interfaces/Viewport.ts
- webAO/viewport/utils/handleICSpeaking.ts
- webAO/viewport/utils/initTestimonyUpdater.ts
- webAO/viewport/utils/setSide.ts
- webAO/viewport/viewport.ts
Had to refactor variables with getters and setters. Logic could probably be more defined in the future, but this is a good place to leave it.
> More function removal from viewport

- webAO/utils/aoml.ts
[User reported issues trying to use the markdown feature of AO.](https://discord.com/channels/278529040497770496/353369729328611330/1096975733924036720) 
Just needed to change around the if else. 
Becomes:
> Resolve Color Identifiers in IC

- webAO/client.ts
i copied it from client so it can now deal with partial packets or multiple packets in one message
> Packet handler

- public/client.html
- webAO/packets/handlers/handleCT.ts
Desktop already does this. Seems very ironic that web doesn't.
And it looks like my formatter hates the client.html file by the way. The only changes in client.html is the inline style for client_ooclog, everything else is just formatting, as well as changing ooc from textarea to div, which might have some interesting side effects.
> Make links in OOC clickable

- public/index.html
- webAO/master.ts
This changes localhost to use connection string instead of ip and fixes some styling around localhost and singleplayer (localhost is no longer red), plus some formatting and minor refactoring in master.ts.
> Localhost connect string

- .eslintrc.js
The whole codebase is formatted with 2 space indentation so update .eslint.js to reflect that.
> Set ESLint indent to 2 spaces
